name: narges_portfolio
description: "Narges Yaghouti"
publish_to: 'none'
version: 1.0.6+6

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gif: ^2.3.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.5
  # sizer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/world1.png
    - assets/prof2.jpeg
    - assets/fonts/
    - assets/gifs/
    - assets/fonts/ProtestStrike-Regular.ttf
  fonts:
    - family: ProtestStrike
      fonts:
        - asset: assets/fonts/ProtestStrike-Regular.ttf
